# Generated by Django 5.2.1 on 2025-05-17 21:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='Horário de Funcionamento')),
                ('history', models.TextField(blank=True, null=True, verbose_name='História')),
                ('patron', models.TextField(blank=True, null=True, verbose_name='Padroeiro')),
                ('mass_schedule', models.TextField(blank=True, null=True, verbose_name='Horário das Missas')),
                ('location_contact', models.TextField(blank=True, null=True, verbose_name='Contato e Localização')),
                ('pastorals_movement', models.TextField(blank=True, null=True, verbose_name='Pastorais e Movimentos')),
                ('confessions', models.TextField(blank=True, null=True, verbose_name='Confissões e atendimentos')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título (padre, bispo, etc.)')),
                ('function', models.CharField(blank=True, max_length=255, null=True, verbose_name='Função (pároco, vigário, etc.)')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Formação e Trajetória')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem para a comunidade')),
                ('photo', models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Foto do padre')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priests', to='church.church')),
            ],
            options={
                'verbose_name': 'Padre',
                'verbose_name_plural': 'Padres',
            },
        ),
    ]
