# Generated by Django 5.2.1 on 2025-05-15 01:24

import church.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('history', models.TextField(blank=True, null=True, verbose_name='História')),
                ('patron', models.TextField(blank=True, null=True, verbose_name='Padroeiro')),
                ('mass_schedule', models.TextField(blank=True, null=True, verbose_name='Horário das Missas')),
                ('location_contact', models.TextField(blank=True, null=True, verbose_name='Contato e Localização')),
                ('pastorals_movement', models.TextField(blank=True, null=True, verbose_name='Pastorais e Movimentos')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
            },
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=church.models.get_file_path, validators=[church.models.validate_image_file], verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priests', to='church.church')),
            ],
        ),
    ]
