# Generated by Django 5.2.1 on 2025-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='church',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Secundária'),
        ),
    ]
