# Generated by Django 5.2.1 on 2025-05-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priest',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Função'),
        ),
    ]
