# Generated by Django 5.2.1 on 2025-05-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_priest_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='confessions',
            field=models.TextField(blank=True, null=True, verbose_name='Confissões e atendimentos'),
        ),
        migrations.AddField(
            model_name='church',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='church',
            name='opening_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='church',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='priest',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='Formação e Trajetória'),
        ),
        migrations.AddField(
            model_name='priest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem para a comunidade'),
        ),
        migrations.AlterField(
            model_name='priest',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Função (pároco, vigário, etc.)'),
        ),
        migrations.AlterField(
            model_name='priest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título (padre, bispo, etc.)'),
        ),
    ]
