# Generated by Django 5.2.1 on 2025-05-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_church_confessions_church_email_church_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name': 'Igreja', 'verbose_name_plural': 'Igrejas'},
        ),
        migrations.AlterModelOptions(
            name='priest',
            options={'verbose_name': 'Padre', 'verbose_name_plural': 'Padres'},
        ),
    ]
