# Generated by Django 5.2 on 2025-05-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_manage_news', 'Pode gerenciar notícias'), ('can_publish_news', 'Pode publicar notícias'), ('can_manage_categories', 'Pode gerenciar categorias'), ('can_manage_images', 'Pode gerenciar imagens')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
