# Generated by Django 5.2.1 on 2025-05-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
