services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - parish_network

  web:
    build: .
    command: uv run gunicorn paroquianews.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    # environment:
    #   - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    #   - DEBUG=False
    #   - ALLOWED_HOSTS=localhost,127.0.0.1
    #   - ENGINE=${ENGINE}
    #   - DB_NAME=${DB_NAME}
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    depends_on:
      - db
    networks:
      - parish_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - parish_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  parish_network:
    driver: bridge