# Generated by Django 5.2.1 on 2025-05-15 01:24

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=news.models.get_file_path, validators=[news.models.validate_image_file], verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da imagem', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('summary', models.TextField(max_length=500, verbose_name='Resumo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=news.models.get_file_path, validators=[news.models.validate_image_file], verbose_name='Imagem de Capa')),
                ('is_published', models.BooleanField(default=False, help_text='Indica se a notícia está publicada', verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, help_text='Indica se a notícia deve aparecer em destaque', verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='church.church')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
    ]
